"""Health records endpoints.

All per-record-type CRUD (POST/GET-list/GET-one/PUT/DELETE) is generated by
``register_record_crud`` against each ``HealthRecordSpec``. This file is just
the spec table for the eight supported record types plus two aggregate
endpoints (``get_health_stats``, ``get_history_timeline``).
"""

from datetime import datetime, timedelta, timezone

from flask import Blueprint, g, jsonify, request
from flask_pydantic_spec import Response

import web.app as app  # use app.db and app.logger so test patches are visible
from web.app import api
from web.decorators import require_pet_access
from web.errors import error_response
from web.health_records_factory import HealthRecordSpec, register_record_crud
from web.schemas import (
    AsthmaAttackCreate,
    AsthmaAttackItem,
    AsthmaAttackListResponse,
    AsthmaAttackUpdate,
    DefecationCreate,
    DefecationItem,
    DefecationListResponse,
    DefecationUpdate,
    EarCleaningCreate,
    EarCleaningItem,
    EarCleaningListResponse,
    EarCleaningUpdate,
    ErrorResponse,
    EyeDropsCreate,
    EyeDropsItem,
    EyeDropsListResponse,
    EyeDropsUpdate,
    FeedingCreate,
    FeedingItem,
    FeedingListResponse,
    FeedingUpdate,
    HealthStatsQuery,
    HealthStatsResponse,
    LitterChangeCreate,
    LitterChangeItem,
    LitterChangeListResponse,
    LitterChangeUpdate,
    TimelineQuery,
    TimelineResponse,
    ToothBrushingCreate,
    ToothBrushingItem,
    ToothBrushingListResponse,
    ToothBrushingUpdate,
    WeightRecordCreate,
    WeightRecordItem,
    WeightRecordListResponse,
    WeightRecordUpdate,
)


health_records_bp = Blueprint("health_records", __name__)


# ---------------------------------------------------------------------------
# Per-record-type document builders
# ---------------------------------------------------------------------------
#
# Each builder turns a *Create schema instance into a MongoDB document.
# They differ only in the default for optional fields, so a couple of lambdas
# and small functions keep them readable without hiding too much in magic.


def _str_or_default(default: str = ""):
    """Return a function that maps ``data.field`` to ``field or default``."""

    def _get(data, field_name):
        return getattr(data, field_name) or default

    return _get


def _asthma(data, pet_id, username, event_dt):
    return {
        "pet_id": pet_id,
        "date_time": event_dt,
        "duration": data.duration or "",
        "reason": data.reason or "",
        "inhalation": data.inhalation,
        "comment": data.comment or "",
        "username": username,
    }


def _defecation(data, pet_id, username, event_dt):
    return {
        "pet_id": pet_id,
        "date_time": event_dt,
        "stool_type": data.stool_type or "",
        "color": data.color or "Коричневый",
        "food": data.food or "",
        "comment": data.comment or "",
        "username": username,
    }


def _litter(data, pet_id, username, event_dt):
    return {
        "pet_id": pet_id,
        "date_time": event_dt,
        "comment": data.comment or "",
        "username": username,
    }


def _weight(data, pet_id, username, event_dt):
    return {
        "pet_id": pet_id,
        "date_time": event_dt,
        "weight": data.weight,
        "food": data.food or "",
        "comment": data.comment or "",
        "username": username,
    }


def _feeding(data, pet_id, username, event_dt):
    return {
        "pet_id": pet_id,
        "date_time": event_dt,
        "food_weight": (
            data.food_weight if data.food_weight is not None else None
        ),
        "comment": data.comment or "",
        "username": username,
    }


def _simple_with_type(type_field: str):
    """Builder for records that have just one extra ``str`` field beyond the base."""

    def _build(data, pet_id, username, event_dt):
        return {
            "pet_id": pet_id,
            "date_time": event_dt,
            type_field: getattr(data, type_field) or "",
            "comment": data.comment or "",
            "username": username,
        }

    return _build


# ---------------------------------------------------------------------------
# Spec table — one entry per supported record type.
# ---------------------------------------------------------------------------

RECORD_SPECS: list[HealthRecordSpec] = [
    HealthRecordSpec(
        endpoint="asthma",
        collection="asthma_attacks",
        log_name="asthma attack",
        msg_prefix="asthma",
        create_schema=AsthmaAttackCreate,
        update_schema=AsthmaAttackUpdate,
        item_schema=AsthmaAttackItem,
        list_response_schema=AsthmaAttackListResponse,
        list_field_name="attacks",
        build_doc=_asthma,
    ),
    HealthRecordSpec(
        endpoint="defecation",
        collection="defecations",
        log_name="defecation",
        msg_prefix="defecation",
        create_schema=DefecationCreate,
        update_schema=DefecationUpdate,
        item_schema=DefecationItem,
        list_response_schema=DefecationListResponse,
        list_field_name="defecations",
        build_doc=_defecation,
    ),
    HealthRecordSpec(
        endpoint="litter",
        collection="litter_changes",
        log_name="litter change",
        msg_prefix="litter",
        create_schema=LitterChangeCreate,
        update_schema=LitterChangeUpdate,
        item_schema=LitterChangeItem,
        list_response_schema=LitterChangeListResponse,
        list_field_name="litter_changes",
        build_doc=_litter,
    ),
    HealthRecordSpec(
        endpoint="weight",
        collection="weights",
        log_name="weight",
        msg_prefix="weight",
        create_schema=WeightRecordCreate,
        update_schema=WeightRecordUpdate,
        item_schema=WeightRecordItem,
        list_response_schema=WeightRecordListResponse,
        list_field_name="weights",
        build_doc=_weight,
    ),
    HealthRecordSpec(
        endpoint="feeding",
        collection="feedings",
        log_name="feeding",
        msg_prefix="feeding",
        create_schema=FeedingCreate,
        update_schema=FeedingUpdate,
        item_schema=FeedingItem,
        list_response_schema=FeedingListResponse,
        list_field_name="feedings",
        build_doc=_feeding,
    ),
    HealthRecordSpec(
        endpoint="eye_drops",
        collection="eye_drops",
        log_name="eye drops",
        msg_prefix="eye_drops",
        create_schema=EyeDropsCreate,
        update_schema=EyeDropsUpdate,
        item_schema=EyeDropsItem,
        list_response_schema=EyeDropsListResponse,
        list_field_name="eye_drops",
        build_doc=_simple_with_type("drops_type"),
    ),
    HealthRecordSpec(
        endpoint="tooth_brushing",
        collection="tooth_brushing",
        log_name="tooth brushing",
        msg_prefix="tooth_brushing",
        create_schema=ToothBrushingCreate,
        update_schema=ToothBrushingUpdate,
        item_schema=ToothBrushingItem,
        list_response_schema=ToothBrushingListResponse,
        list_field_name="tooth_brushing",
        build_doc=_simple_with_type("brushing_type"),
    ),
    HealthRecordSpec(
        endpoint="ear_cleaning",
        collection="ear_cleaning",
        log_name="ear cleaning",
        msg_prefix="ear_cleaning",
        create_schema=EarCleaningCreate,
        update_schema=EarCleaningUpdate,
        item_schema=EarCleaningItem,
        list_response_schema=EarCleaningListResponse,
        list_field_name="ear_cleaning",
        build_doc=_simple_with_type("cleaning_type"),
    ),
]


for _spec in RECORD_SPECS:
    register_record_crud(health_records_bp, _spec)


# ---------------------------------------------------------------------------
# Aggregate endpoints (stats + timeline) — not per-record-type CRUD, so
# they live here rather than in the factory.
# ---------------------------------------------------------------------------


@health_records_bp.route("/api/stats/health", methods=["GET"])
@api.validate(
    query=HealthStatsQuery,
    resp=Response(HTTP_200=HealthStatsResponse, HTTP_422=ErrorResponse, HTTP_403=ErrorResponse),
    tags=["stats"],
)
@require_pet_access
def get_health_stats():
    """Get health statistics for charts."""
    query_params = request.context.query  # type: ignore[attr-defined]
    pet_id = g.pet_id
    record_type = query_params.type
    days = query_params.days or 30

    # Map record types to collection names and value fields
    type_mapping = {
        "feeding": ("feedings", "food_weight"),
        "asthma": ("asthma_attacks", "count"),
        "defecation": ("defecations", "count"),
        "litter": ("litter_changes", "count"),
        "weight": ("weights", "weight"),
        "eye_drops": ("eye_drops", "count"),
        "tooth_brushing": ("tooth_brushing", "count"),
        "ear_cleaning": ("ear_cleaning", "count"),
        "medications": ("medication_intakes", "count"),
    }

    if record_type not in type_mapping:
        return error_response("invalid_type", f"Unsupported record type: {record_type}")

    collection_name, value_field = type_mapping[record_type]

    # Calculate date range
    since_date = datetime.now(timezone.utc) - timedelta(days=days)

    # Fetch records
    records = list(
        app.db[collection_name]
        .find({"pet_id": pet_id, "date_time": {"$gte": since_date}})
        .sort("date_time", 1)
    )

    stats_data = []
    for record in records:
        dt = record.get("date_time")
        if isinstance(dt, datetime):
            date_str = dt.strftime("%Y-%m-%d %H:%M")
        else:
            date_str = str(dt)

        value = 1 if value_field == "count" else record.get(value_field, 0)
        stats_data.append({"date": date_str, "value": value})

    return jsonify({"data": stats_data})


@health_records_bp.route("/api/history/timeline", methods=["GET"])
@api.validate(
    query=TimelineQuery,
    resp=Response(HTTP_200=TimelineResponse, HTTP_422=ErrorResponse, HTTP_403=ErrorResponse),
    tags=["health-records"],
)
@require_pet_access
def get_history_timeline():
    """Get aggregate timeline of all health records and medication intakes for a pet."""
    query_params = request.context.query  # type: ignore[attr-defined]
    pet_id = g.pet_id
    page = query_params.page
    page_size = query_params.page_size
    filter_type = getattr(query_params, "type", "all")

    collections = {
        "feedings": "feeding",
        "asthma_attacks": "asthma",
        "defecations": "defecation",
        "litter_changes": "litter",
        "weights": "weight",
        "eye_drops": "eye_drops",
        "tooth_brushing": "tooth_brushing",
        "ear_cleaning": "ear_cleaning",
        "medication_intakes": "medications",
    }

    # Filter collections if a specific type is requested
    if filter_type and filter_type != "all":
        collections = {k: v for k, v in collections.items() if v == filter_type}

    all_records = []

    for coll_name, record_type in collections.items():
        try:
            records_cursor = app.db[coll_name].find({"pet_id": pet_id})
            for record in records_cursor:
                record["_id"] = str(record["_id"])
                record["pet_id"] = str(record.get("pet_id", ""))
                record["record_type"] = record_type

                if isinstance(record.get("date_time"), datetime):
                    record["date_time"] = record["date_time"].strftime("%Y-%m-%d %H:%M")

                if record_type == "medications" and "medication_id" in record:
                    from bson import ObjectId  # local import keeps module-load cheap
                    med = app.db["medications"].find_one({"_id": ObjectId(record["medication_id"])})
                    if med:
                        record["medication_name"] = med.get("name", "Unknown")

                all_records.append(record)
        except Exception as e:
            app.logger.warning(f"Error fetching from {coll_name} for timeline: {e}")

    # Sort all records by date_time descending
    all_records.sort(key=lambda x: x.get("date_time", ""), reverse=True)

    # Apply pagination in memory
    total = len(all_records)
    offset = (page - 1) * page_size
    paginated_records = all_records[offset:offset + page_size]

    return jsonify(
        {
            "items": paginated_records,
            "page": page,
            "page_size": page_size,
            "total": total,
        }
    )